language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - psql -c 'CREATE DATABASE kawalya;' -U postgres
  -  psql -c 'CREATE DATABASE question_test;' -U postgres

  # - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U kawalya#

script:
  - nosetests --with-coverage --cover-package=app app/tests

after_success:
  - coveralls
  #- codecov --token=
