language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

services:
  - postgresql
addons:
  postgresql: "10.5"

before_script:
  - sql -c 'CREATE DATABASE kawalya' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres

script:
  - nosetests --with-coverage --cover-package=app app/tests

after_success:
  - coveralls
  - codecov --token=
